language: rust
rust:
- nightly
cache:
- cargo
before_install:
- shopt -s globstar
- MAX_LINE_LENGTH=100 bash ci/check_line_lengths.sh src/**/*.md
install:
- source ~/.cargo/env || true
- bash ci/install.sh
script:
- mdbook build
- mdbook test
notifications:
  email:
    on_success: never
env:
  global:
  - secure: NZaqZBxqGznEDI3W/asPe80lRBw+RSHaGsgE79cz4HhAjDvqm1SkEOvo7WBs3rGEFfip08UAkiAC9ujqaTlUOl+w/BFAuxldG8eOj16ewSgK/uzFxG++1O3hhMDg+HOg2GVI+yDY92k2G/38XsHmW1tcdApMdeRmvZG195uoi9s5X+PK4DC3ZLjgyqpCxYJIjkUGOpgBn+y909ZK3VxD93zF9T9hDHUf3mx8es1Jh7Jw9WIt7vgEMTpWzGNfV/0WyBcu+1HzOFCgGYkLmNBqNOX40/ZpUz6OZQQ0CJisy02JZ2aeRalWMz+cVj8UqL42kKCczaRqs/3wwmTuKrxPPeO/8fChJOTsO9/5PdpGxUP+UZ/QGPr83L+QujKC/gRKgIMWs/a+ckd90wglwyOorJSm1PzxCy9497ZKUFT2XDYXoqYltRCEhGGbwIHXxOxqTpTijIJiHQ1FUlp2GKvJXIDzbavpGZGc3LWW8JR3WfrEJTuzACHg2rBZLqMwF63cpvCvA2pf37hiclIAO1rCp3AumQHr7QdsLS2bCbW7vlg/QhI82utzuxOaBXihNa6OhpkeBU0BaV3UdzdB2rHLssqrp0ni3RwDhP77plBgKRDFSd/V/oQEygBgjhQ8JqDMKGBglZZSoHbq61TwtWXn8irYVeKcFWMFpfjHfzt7pvw=
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: book/html
  on:
    branch: master
