language: rust
rust:
- nightly
cache:
- cargo
before_install:
- shopt -s globstar
- MAX_LINE_LENGTH=100 bash ci/check_line_lengths.sh src/**/*.md
install:
- source ~/.cargo/env || true
- bash ci/install.sh
script:
- mdbook build
- mdbook test
notifications:
  email:
    on_success: never
env:
  global:
  - secure: myJlqevjvj/AfJ7aHcQ+DrAh5YUw0JWARAVAX6lMI9AYl30ht3eJJ82mLkiLBVKgLqUuXQVvEYfRYORFLfKbDhlufUW+5xOxYTdeLY2Q+4aPwsJNFZ7WHbcIGrdgKioDgDvpL2QOTKw7sfy+vq+02XiGwUAHvh5B08lD6Cn7EtrNEgZx3kKivY6HJ0k8VU8vBKKN4iW/etXS7E+OyFIcTbTJX16HZgGy1uLgSyoTv15BD0I+7fPa0PNmjzzpoky/+M+lVhYEx9lPRdKOgVknoXoAxqSJUUzVMBb1SSPFSMf8xEBGUhnRCe0sz/wGDpfpBvG4b3sL+cG6VfjSVEEtICimjlz7mQVf9C8VtDBq3jwNwsRf9UYoEwY12bWS4CsPQftclUysn4Ww5G/uDIv8U6BQrOWMP1evBJg1vq20r4m58f9E+pptLN2QdR+B+10jRWtY8lUAwGGlS4U3eNhhzlSuOTlrWBUuTzvFifIpoLrOowgE+Vebtu2W0Lii90yADTns1tCvy7Aa72JxxnlzAZ60OQznLXJtSW4I5oD0b+Wi6YRIqBDjcewQVQJIkIc4qZiOZ5zMD9gpQZgp8EcH3FASnMXDOFUbuEijKKXEH9VnP/j9WN8+fbTa1WX3YwnbrhbXTE0c6kwvYpwrdzZDbHf/sqFiMypJeBEclSoOhy8=
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: book/html
  on:
    branch: master
