[book]
title = "Rustc 开发指南"
author = "Rustc 开发者"
description = "Rustc 开发指南"
src = "src-zh"

[output.html]

[output.html.search]

[output.linkcheck]
follow-web-links = true
exclude = [ "crates\\.io", "gcc\\.godbolt\\.org" ]
